name: main

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "bash -euo pipefail {0}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Ensure files are auto-formatted
        run: npm run prettier-check
      - name: Lint Typescript code
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build
        run: |
          rm -rf dist
          npm run webpack-prod
      - name: Create Browser Extension zip archives
        run: npm run assemble-release-files
        if: startsWith(github.ref, 'refs/tags/') || github.ref_name == 'ci'
      - name: Create GitHub Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            headgear-*
            RELEASE.txt*
          fail_on_unmatched_files: true
          draft: true
